version: "2.1"
services:
  app:
    image: node:22.6.0-slim
    container_name: putlocker-node
    entrypoint: ['node', "--inspect=0.0.0.0:${DEBUG_PORT}", 'src/index.js']
    working_dir: /app
    volumes:
      - ${PWD}:/app
    ports:
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      NODE_ENV: development
      PUTLOCKER_SITE: ${PUTLOCKER_SITE}
      DOWNLOADS_DIR: ${DOWNLOADS_DIR}
      SEASON_URL: ${SEASON_URL}
    restart: on-failure
